import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Navigation from "@/components/Navigation";
import { styles } from "@/styles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable}  ${styles.bodyBgColor} ${styles.textDefault} antialiased lg:h-screen lg:overflow-y-hidden relative`}
      >
        <Navigation />
        <div className={"relative lg:h-[calc(100vh-6.5rem)]"}>{children}</div>
      </body>
    </html>
  );
}
