import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Navigation from "@/components/Navigation";
import { styles } from "@/styles";
import { Providers } from "@/app/providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={` ${styles.bodyBgColor} ${styles.textDefault} antialiased lg:h-screen lg:overflow-y-hidden relative`}
      >
        <Providers>
          <Navigation />
          <div className={"relative lg:h-[calc(100vh-6.5rem)]"}>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
